title: Jenny Ji Park
description: 개발 공부도 하고 일상도 올리는 그런 devlog
author: Jenny JI Park
avatar: ./image/01.JPG
email: jennyjipark@gmail.com
skin: daylight.scss

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
#
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
#
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username:
  card: summary
logo: logo.png
social:
  name: Jenny Ji Park
  links:
    - https://github.com/jennyjipark
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
